# Generated by Django 3.0.10 on 2022-08-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desarrolladores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('campus', models.CharField(max_length=50)),
            ],
        ),
    ]
